#!/bin/bash

echo "#"
echo "# Installing Ogre"
echo "#"

echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list
apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
apt-get update
sudo apt-get -y install docker-engine
service docker start

#wget http://54.242.169.245/chrome31.tar.gz
wget https://s3.amazonaws.com/bn-docker-bDXqSVIGc2isXGp14fDf/chrome31.tar.gz
gunzip -c chrome31.tar.gz | docker load

mkdir -p /tmp/docker
cp hooks/check.rb /tmp/docker
cp hooks/run.sh /tmp/docker
chmod +x /tmp/docker/check.rb
chmod +x /tmp/docker/run.sh

echo "Done!"
