apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: kurento
  name: kurento
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: kurento
    spec:
      containers:
      - env:
        - name: KMS_STUN_IP
          value: 206.47.241.9
        - name: KMS_STUN_PORT
          value: "3478"
        image: bbb-kurento
        name: kurento
        resources: {}
        volumeMounts:
        - mountPath: /var/kurento/recordings
          name: media-video
        - mountPath: /var/kurento/screenshare
          name: media-screenshare
      restartPolicy: Always
      volumes:
      - name: media-video
        persistentVolumeClaim:
          claimName: media-video
      - name: media-screenshare
        persistentVolumeClaim:
          claimName: media-screenshare
status: {}
