apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
  namespace: bigbluebutton
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - args:
        - traefik
        - '-'
        - --docker
        - '-'
        - --logLevel=INFO
        - '-'
        - --acme
        - '-'
        - --acme.httpchallenge
        - '-'
        - --acme.httpchallenge.entrypoint=http
        - '-'
        - --acme.acmelogging
        - '-'
        - --acme.storage=/etc/traefik/acme/acme.json
        - '-'
        - --acme.email=felipe@mconf.com
        - '-'
        - --acme.entrypoint=https
        - '-'
        - --acme.domains=romania.cdot.systems
        - '-'
        - --defaultentrypoints=http,https
        - '-'
        - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
        - '-'
        - --entryPoints=Name:https Address::443 TLS
        image: traefik
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/traefik/acme/
          name: traefik-acme
        - mountPath: /var/run/docker.sock
          name: traefik-claim1
      restartPolicy: Always
      volumes:
      - name: traefik-acme
        persistentVolumeClaim:
          claimName: traefik-acme
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
  namespace: bigbluebutton
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: traefik
status:
  loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: traefik-acme
  name: traefik-acme
  namespace: bigbluebutton
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: traefik-claim1
  name: traefik-claim1
  namespace: bigbluebutton
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
