version: '2'

# export SERVER_DOMAIN=felipe.dev.mconf.com
# export EXTERNAL_IP=`dig +short $SERVER_DOMAIN`
# export SHARED_SECRET=`openssl rand -hex 16`
# export COTURN_REST_SECRET=`openssl rand -hex 16`
# export SCREENSHARE_EXTENSION_LINK=https://chrome.google.com/webstore/detail/mconf-screenshare/mbfngdphjegmlbfobcblikeefpidfncb
# export SCREENSHARE_EXTENSION_KEY=mbfngdphjegmlbfobcblikeefpidfncb

services:
  mongo:
    image: mongo:3.4
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  bbb-html5:
    image: bbb-html5
    restart: unless-stopped
    links:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo/bbbhtml5
      METEOR_SETTINGS_MODIFIER: ".public.kurento.wsUrl = \"wss://${SERVER_DOMAIN}/bbb-webrtc-sfu\" | .public.kurento.enableVideo = true | .public.kurento.enableScreensharing = true | .public.kurento.chromeDefaultExtensionKey = \"${SCREENSHARE_EXTENSION_KEY}\" | .public.kurento.chromeDefaultExtensionLink = \"${SCREENSHARE_EXTENSION_LINK}\""
      REDIS_HOST: redis
      ROOT_URL: http://127.0.0.1/html5client

  bbb-webhooks:
    image: bbb-webhooks
    restart: unless-stopped
    links:
      - redis
    environment:
      REDIS_HOST: redis
      SHARED_SECRET: ${SHARED_SECRET}

  bbb-freeswitch:
    image: bbb-freeswitch
    restart: unless-stopped
    links:
      - coturn

  bbb-webrtc-sfu:
    image: bbb-webrtc-sfu
    restart: unless-stopped
    links:
      - redis
      - kurento
    environment:
      KURENTO_IP: ${EXTERNAL_IP}
      KURENTO_URL: ws://kurento:8888/kurento
      REDIS_HOST: redis

  coturn:
    image: coturn
    restart: unless-stopped
    volumes:
      - ssl-conf:/etc/nginx/ssl
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SSL_CERT_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/fullchain.pem
      SSL_KEY_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/privkey.pem
      SSL_DHPARAM_PATH: /etc/nginx/ssl/dhp-2048.pem
      SECRET: ${COTURN_REST_SECRET}
      EXTERNAL_IP: ${EXTERNAL_IP}
      ENABLE_REST_API: 1
      PORT: 3478
      PORT_TLS: 5349
    ports:
      - 3478:3478/udp
      - 3478:3478/tcp
      - 5349:5349/tcp

  kurento:
    image: kurento
    restart: unless-stopped
    environment:
      KMS_STUN_IP: ${EXTERNAL_IP}
      KMS_STUN_PORT: 3478

  bbb-apps-akka:
    image: bbb-apps-akka
    restart: unless-stopped
    links:
      - redis
    environment:
      JAVA_OPTS: -Dredis.host=redis

  bbb-fsesl-akka:
    image: bbb-fsesl-akka
    restart: unless-stopped
    links:
      - bbb-freeswitch
      - redis
    environment:
      JAVA_OPTS: -Dredis.host=redis -Dfreeswitch.esl.host=bbb-freeswitch

  bbb-web:
    image: bbb-web
    restart: unless-stopped
    links:
      - redis
    volumes:
      - bigbluebutton:/var/bigbluebutton
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SHARED_SECRET: ${SHARED_SECRET}
      TURN_SECRET: ${COTURN_REST_SECRET}

#  greenlight-env:
#    image: bigbluebutton/greenlight
#    volumes:
#      - config-greenlight:/data
#    command: rake secret > /data/env

#  greenlight:
#    image: bigbluebutton/greenlight
#    restart: unless-stopped
#    volumes:
#      - db-greenlight:/usr/src/app/db/production

  nginx:
    image: nginx
    restart: unless-stopped
    links:
      - bbb-webhooks
      - bbb-web
      - bbb-html5
      - bbb-webrtc-sfu
      - bbb-freeswitch
#      - greenlight
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-conf:/etc/nginx/ssl
      - static:/var/www/bigbluebutton-default
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SSL_CERT_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/fullchain.pem
      SSL_KEY_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/privkey.pem
      SSL_DHPARAM_PATH: /etc/nginx/ssl/dhp-2048.pem

volumes:
  ssl-conf:
    driver: local    
  static:
    driver: local    
  bigbluebutton:
