version: '2'

services:
  mongo:
    image: mongo:3.4
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  bbb-html5:
    image: ${TAG_PREFIX}bbb-html5${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    environment:
      MONGO_URL: mongodb://mongo/bbbhtml5
      METEOR_SETTINGS_MODIFIER: ".public.kurento.wsUrl = \"wss://${SERVER_DOMAIN}/bbb-webrtc-sfu\" | .public.kurento.enableVideo = true | .public.kurento.enableScreensharing = true | .public.kurento.chromeDefaultExtensionKey = \"${SCREENSHARE_EXTENSION_KEY}\" | .public.kurento.chromeDefaultExtensionLink = \"${SCREENSHARE_EXTENSION_LINK}\" | .public.kurento.enableVideoStats = true | .public.kurento.enableListenOnly = true"
      REDIS_HOST: redis
      ROOT_URL: http://127.0.0.1/html5client

  bbb-webhooks:
    image: ${TAG_PREFIX}bbb-webhooks${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      SHARED_SECRET: ${SHARED_SECRET}

  bbb-freeswitch:
    image: ${TAG_PREFIX}bbb-freeswitch${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - coturn
    volumes:
      - media-audio:/var/freeswitch/meetings

  bbb-webrtc-sfu:
    image: ${TAG_PREFIX}bbb-webrtc-sfu${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - redis
      - kurento
      - bbb-freeswitch
    environment:
      KURENTO_NAME: kurento
      KURENTO_URL: ws://kurento:8888/kurento
      REDIS_HOST: redis
      FREESWITCH_IP: bbb-freeswitch
      LOG_LEVEL: debug

  coturn:
    image: ${TAG_PREFIX}coturn${TAG_SUFFIX}
    restart: unless-stopped
    volumes:
      - ssl-conf:/etc/nginx/ssl
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SSL_CERT_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/fullchain.pem
      SSL_KEY_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/privkey.pem
      SSL_DHPARAM_PATH: /etc/nginx/ssl/dhp-2048.pem
      SECRET: ${COTURN_REST_SECRET}
      EXTERNAL_IP: ${EXTERNAL_IP}
      ENABLE_REST_API: 1
      PORT: 3478
      PORT_TLS: 5349
    ports:
      - 3478:3478/udp
      - 3478:3478/tcp
      - 5349:5349/tcp

  kurento:
    image: ${TAG_PREFIX}kurento${TAG_SUFFIX}
    restart: unless-stopped
    volumes:
      - media-video:/var/kurento/recordings
      - media-screenshare:/var/kurento/screenshare
    environment:
      KMS_STUN_IP: ${EXTERNAL_IP}
      KMS_STUN_PORT: 3478

  bbb-apps-akka:
    image: ${TAG_PREFIX}bbb-apps-akka${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      JAVA_OPTS: -Dredis.host=redis

  bbb-fsesl-akka:
    image: ${TAG_PREFIX}bbb-fsesl-akka${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - bbb-freeswitch
      - redis
    command: ["wait-for-it.sh", "bbb-freeswitch:8021", "--timeout=60", "--strict", "--", "/usr/share/bbb-fsesl-akka/bin/bbb-fsesl-akka"]
    environment:
      JAVA_OPTS: -Dredis.host=redis -Dfreeswitch.esl.host=bbb-freeswitch

  bbb-web:
    image: ${TAG_PREFIX}bbb-web${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - bigbluebutton:/var/bigbluebutton
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SHARED_SECRET: ${SHARED_SECRET}
      TURN_SECRET: ${COTURN_REST_SECRET}

#  greenlight-env:
#    image: bigbluebutton/greenlight
#    volumes:
#      - config-greenlight:/data
#    command: rake secret > /data/env

#  greenlight:
#    image: bigbluebutton/greenlight
#    restart: unless-stopped
#    volumes:
#      - db-greenlight:/usr/src/app/db/production

  nginx:
    image: ${TAG_PREFIX}nginx${TAG_SUFFIX}
    restart: unless-stopped
    depends_on:
      - bbb-webhooks
      - bbb-web
      - bbb-html5
      - bbb-webrtc-sfu
      - bbb-freeswitch
#      - greenlight
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-conf:/etc/nginx/ssl
      - static:/var/www/bigbluebutton-default
    environment:
      SERVER_DOMAIN: ${SERVER_DOMAIN}
      SSL_CERT_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/fullchain.pem
      SSL_KEY_PATH: /etc/nginx/ssl/live/${SERVER_DOMAIN}/privkey.pem
      SSL_DHPARAM_PATH: /etc/nginx/ssl/dhp-2048.pem

volumes:
  ssl-conf:
  static:
  bigbluebutton:
  media-audio:
  media-video:
  media-screenshare:
