version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
    container_name: greenlight-v2
    env_file: env
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./db/production:/usr/src/app/db/production
      - ./log:/usr/src/app/log
